export const APP_NAME = 'Urbanico';

export const BRAND_LOGO_URL = 'https://res.cloudinary.com/dfr0zghtc/image/upload/v1790148105/logolatest_avkcr1.jpg';

export const INDIAN_STATES = [
  'Telangana',
  'Andhra Pradesh',
  'Karnataka',
  'Maharashtra',
  'Tamil Nadu',
  'Delhi NCR',
  'Gujarat',
  'Rajasthan',
  'Uttar Pradesh',
  'West Bengal',
  'Kerala',
  'Madhya Pradesh',
  'Haryana',
  'Punjab',
  'Bihar',
  'Odisha',
  'Assam',
  'Goa',
  'Jharkhand',
  'Chhattisgarh',
  'Uttarakhand',
  'Himachal Pradesh',
  'Chandigarh',
  'Puducherry',
  'Jammu & Kashmir',
] as const;

export const ADDRESS_TYPE_OPTIONS = [
  { id: 'Site', label: 'Site / Project', icon: 'Building2' },
  { id: 'Home', label: 'Home', icon: 'Home' },
  { id: 'Office', label: 'Office', icon: 'Briefcase' },
  { id: 'Warehouse', label: 'Warehouse / Yard', icon: 'Warehouse' },
] as const;

export const POPULAR_SEARCH_SUGGESTIONS = [
  'Vitrified Double Charge Tiles',
  'UltraTech Cement 53 Grade',
  'Plastering Sand',
  'TMT 12mm Rebar',
  'Red Clay Bricks',
  'Stone 20mm',
  'Ceramic Wall Tiles',
];

export const CATEGORY_SEARCH_MAP: Record<string, string> = {
  tile: 'tiles',
  tiles: 'tiles',
  vitrified: 'tiles',
  ceramic: 'tiles',
  flooring: 'tiles',
  paver: 'tiles',
  sand: 'sand',
  river: 'sand',
  'm-sand': 'sand',
  robo: 'sand',
  plastering: 'sand',
  brick: 'bricks',
  bricks: 'bricks',
  clay: 'bricks',
  aac: 'bricks',
  blocks: 'bricks',
  cement: 'cement',
  ultratech: 'cement',
  ambuja: 'cement',
  acc: 'cement',
  birla: 'cement',
  stone: 'stone',
  gravel: 'stone',
  aggregate: 'stone',
  dust: 'stone',
  metal: 'stone',
  iron: 'iron_bars',
  rebar: 'iron_bars',
  tmt: 'iron_bars',
  steel: 'iron_bars',
  bars: 'iron_bars',
  wire: 'iron_bars',
  centring: 'centring',
  centering: 'centring',
  plywood: 'centring',
  bamboo: 'centring',
  shuttering: 'centring',
  formwork: 'centring',
  mason: 'services-catalog',
  fabricator: 'services-catalog',
  painter: 'services-catalog',
  electrician: 'services-catalog',
  plumber: 'services-catalog',
  carpenter: 'services-catalog',
  service: 'services-catalog',
  services: 'services-catalog',
};
